# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: New Books at the LBCC Library
email: libref@linnbenton.edu
description: >- # this means to ignore newlines until "baseurl:"
  Pick up one of these books today!https://libfind.linnbenton.edu:4430/catalog/98803
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://newbooks.lbcc.linnlibraries.org" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: lbcc_library
facebook_username: lbcclibrary
github_username:  lbcclib

# Build settings
theme: minima

cover_image_host: covers.openlibrary.org
cover_image_prefix: b/ISBN/
cover_image_suffix: -M.jpg
cover_image_mime_type: image/jpeg

departments:
  -
    name: Accounting Department
    emails: ACCOUNTING_EMAILS
    discipline: Accounting
  -
    name: Agriculture Department
    emails: AGRICULTURE_EMAILS
    discipline: Agriculture
  -
    name: Anthropology Department
    emails: ANTH_EMAILS
    discipline: Anthropology
  -
    name: Automotive Technology Department
    emails: AUTO_TECH_EMAILS
    discipline: Automotive technology
  -
    name: Biology Department
    emails: BIO_EMAILS
    discipline: Biology
  -
    name: Business Department
    emails: BUSINESS_EMAILS
    discipline: Business
  -
    name: Center for Accessibility Resources
    emails: CFAR_EMAILS
    discipline: Accessibility
  -
    name: Ceramics Faculty
    emails: CERAMICS_EMAILS
    discipline: Ceramics
  -
    name: Communication Department
    emails: COMM_EMAILS
    discipline: Communication
  -
    name: Computer Science Department
    emails: CS_EMAILS
    discipline: Computer science
  -
    name: Counseling Department
    emails: COUNSELING_EMAILS
    discipline: Counseling
  -
    name: Criminal Justice Department
    emails: CJ_EMAILS
    discipline: Criminal justice
  -
    name: Culinary Arts Department
    emails: CULINARY_EMAILS
    discipline: Culinary arts
  -
    name: Dental Assistant Department
    emails: DENTAL_EMAILS
    discipline: Dental assisting
  -
    name: Diagnostic Imaging Department
    emails: DI_EMAILS
    discipline: Diagnostic imaging
  -
    name: Drafting and Engineering Graphics Department
    emails: DRAFTING_EMAILS
    discipline: Drafting and engineering graphics
  -
    name: Education and HDFS Department
    emails: EDUCATION_EMAILS
    discipline: Education and HDFS
  -
    name: ELA Department
    emails: ELA_EMAILS
    discipline: English Language Acquisition
  -
    name: Engineering Department
    emails: ENGINEERING_EMAILS
    discipline: Engineering
  -
    name: English and Writing Department
    emails: ENGLISH_EMAILS
    discipline: English and writing
  -
    name: Equine Science Department
    emails: EQUINE_EMAILS
    discipline: Equine science
  -
    name: Film Studies Interest Group
    emails: FILM_EMAILS
    discipline: Film studies
  -
    name: Earth Sciences Department
    emails: EARTH_EMAILS
    discipline: Earth sciences
  -
    name: Health, Human Performance, Athletics and PE Department
    emails: HHP_EMAILS
    discipline: Health, Human Performance, Athletics and PE
  -
    name: Heavy Equipment/Diesel Department
    emails: DIESEL_EMAILS
    discipline: Heavy equipment/diesel
  -
    name: History Department
    emails: HISTORY_EMAILS
    discipline: History
  -
    name: International Admissions Department
    emails: INTERNATIONAL_EMAILS
    discipline: International admissions
  -
    name: Journalism Department
    emails: JOURNALISM_EMAILS
    discipline: Journalism
  -
    name: Machine Tool Department
    emails: MACHINE_TOOL_EMAILS
    discipline: Machine tool
  -
    name: Math Department
    emails: MATH_EMAILS
    discipline: Math
  -
    name: Mechatronics
    emails: MECHATRONICS_EMAILS
    discipline: Mechatronics
  -
    name: Medical Assisting Department
    emails: MA_EMAILS
    discipline: Medical assisting
  -
    name: Music Department
    emails: MUSIC_EMAILS
    discipline: Music
  -
    name: Non-Destructive Testing Department
    emails: NDT_EMAILS
    discipline: Non-destructive testing
  -
    name: Nursing and CNA Department
    emails: NURSING_EMAILS
    discipline: Nursing
  -
    name: Occupational Therapy Assistant Department
    emails: OTA_EMAILS
    discipline: Occupational therapy
  -
    name: Philosophy Department
    emails: PHILOSOPHY_EMAILS
    discipline: Philosophy
  -
    name: Physical Sciences Department
    emails: PHYSICAL_SCIENCES_EMAILS
    discipline: Physical sciences
  -
    name: Polysomnographic Technology Department
    emails: SLEEP_EMAILS
    discipline: Polysomnographic technology
  -
    name: Psychology Department
    emails: PSYCH_EMAILS
    discipline: Psychology
  -
    name: Public Safety Office
    emails: PUBLIC_SAFETY_EMAILS
    discipline: Public safety
  -
    name: Queer Studies
    emails: QUEER_STUDIES_EMAILS
    discipline: Queer studies
  -
    name: Religion Department
    emails: RELIGION_EMAILS
    discipline: Religion
  -
    name: Small Business Development Center
    emails: SBDC_EMAILS
    discipline: Small Business
  -
    name: Sociology Department
    emails: SOC_EMAILS
    discipline: Sociology
  -
    name: Surgical Tech
    emails: SURGICAL_EMAILS
    discipline: Surgery
  -
    name: PACE
    emails: PACE_EMAILS
    discipline: Equity, diversity, and inclusion
  -
    name: Visual Arts Department
    emails: ART_EMAILS
    discipline: Visual arts
  -
    name: Visual Communication Program
    emails: VISCOM_EMAILS
    discipline: Visual communication
  -
    name: Web Team
    emails: WEB_TEAM_EMAILS
    discipline: Web technologies
  -
    name: Welding Department
    emails: WELDING_EMAILS
    discipline: Welding
  -
    name: Women's Studies Department
    emails: WOMENS_STUDIES_EMAILS
    discipline: Women's Studies


min_items_per_email: 1
max_items_per_email: 40
smtp_server: smtp.gmail.com
smtp_port: 587
link: http://notifications.lbcc.linnlibraries.org

num_items_to_fetch: 140
opac_host: libcat.linnbenton.edu
org_unit: LBCC
